package output

import (
	"aws-bassh/pkg/model"
	_ "embed"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

//go:embed bash-function-template.sh
var bashFunctionTemplate string

type bashFunction struct {
	FunctionName string
	MachineData  string
	AwsbasshExec string
	AwsProfile   string
	ForceBastion bool
}

func WriteMachines(config model.GenerateConfig, machines map[string]model.Machine) bool {
	outputFile := openOutputFile(config)

	if outputFile == nil {
		return false
	}

	defer outputFile.Close()

	writeFileHeader(outputFile)
	return writeMachinesFunctions(config, machines, outputFile)
}

func openOutputFile(config model.GenerateConfig) *os.File {
	file, err := os.Create(config.OutputFile)

	if err != nil {
		log.Printf("Error openning file %v, %v", config.OutputFile, err)
		return nil
	}

	return file
}

func writeFileHeader(outputFile *os.File) {
	outputFile.WriteString("#!/bin/bash\n#\n")
	outputFile.WriteString("# Auto generated by " + os.Args[0] + "\n#\n\n")
}

func writeMachinesFunctions(config model.GenerateConfig, machines map[string]model.Machine, outputFile *os.File) bool {
	tmpl, err := parseBashFunctionTemplate()

	if err != nil {
		return false
	}

	duplications := buildDuplicationsMap(machines)

	for _, machine := range machines {
		bashFunction := getMachineFunction(config, machine, duplications)

		if err := tmpl.Execute(outputFile, bashFunction); err != nil {
			log.Printf("Error executing template for %v %v", bashFunction, err)
		}
	}

	return true
}

func buildDuplicationsMap(machines map[string]model.Machine) map[string]int {
	var duplications map[string]int
	duplications = make(map[string]int)

	for _, machine := range machines {
		duplications[machine.Name] = duplications[machine.Name] + 1
	}

	return duplications
}

func parseBashFunctionTemplate() (*template.Template, error) {
	tmpl, err := template.New("bash function").Parse(bashFunctionTemplate)

	if err != nil {
		log.Printf("Error parsing bash function template %v", err)
		return nil, err
	}

	return tmpl, nil
}

func getMachineFunction(config model.GenerateConfig, machine model.Machine, duplications map[string]int) bashFunction {
	return bashFunction{
		FunctionName: normalizeMachineName(config.BashAliasPrefix + getMachineName(machine, duplications)),
		MachineData:  model.SerializeMachine(machine),
		AwsbasshExec: getAwsbasshPath(),
		AwsProfile:   config.AwsProfile,
		ForceBastion: config.ForceBastion,
	}
}

func getMachineName(machine model.Machine, duplications map[string]int) string {
	if duplications[machine.Name] > 1 {
		return machine.Name + "-" + machine.Id
	} else {
		return machine.Name
	}
}

func normalizeMachineName(machineName string) string {
	reg, err := regexp.Compile("[^a-zA-Z_0-9-]")

	if err != nil {
		log.Printf("Error compiling machine name normailizer regex %v", err)
		return machineName
	}

	return reg.ReplaceAllString(machineName, "_")
}

func getAwsbasshPath() string {
	if !strings.HasPrefix(os.Args[0], ".") {
		return os.Args[0]
	}

	path, err := filepath.Abs(os.Args[0])

	if err != nil {
		log.Printf("Error getting absolute path of %v", os.Args[0])
		return os.Args[0]
	}

	return path
}
